spring:
  application:
    name: app
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
# it's not a real project and i don't want to bother myself with secrets configuration
# DO NOT STORE KEYS IN THE RESOURCES
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG